image:
  file: .gitpod.dockerfile
ports:
- port: 8001
  onOpen: notify
- port: 8002
  onOpen: notify
- port: 5432
  onOpen: ignore
- port: 3306
  onOpen: ignore
tasks:
- name: Logs
  command: >
    pg_start.sh;
    apachectl start;
    psql
    create role postgres with password 'postgres';
    alter user postgres with login superuser;
    \c postgres postgres;
    CREATE DATABASE tce;
    GRANT ALL PRIVILEGES ON DATABASE tce TO postgres;
    \c tce
    create schema if NOT EXISTS iegm;
    \q
    pg_restore remessa.backup;
    mvn spring-boot:run;
    clear;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log -I ~/pg/log/pgsql.log;
- name: Terminal
  command: >
    clear;
    echo "Commands:";
    echo " * pg_start.sh";
    echo " * pg_stop.sh";
